---
title: "COMPSCIX 415.2 Homework 1"
author: "Jackie Lang"
date: "February 2, 2018"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mdsr)
library(tidyverse)
```
My github repository for my assignments can be found at this URL: https://github.com/jrlangberkeley/compscix-415-2-assignments

```{r load_packages, warning=FALSE, message=FALSE}
data("WorldCities")
```

```{r}
glimpse(WorldCities)
data("WorldCities")
```
```{r}
data(WorldCities)
Worldcities<-head(WorldCities, 200)#200 rows
country_col<-WorldCities$country
unique(country_col)
```
```{r}
data(WorldCities)
region_col<-WorldCities$region
unique(region_col)
```
```{r}
data(WorldCities)
country_col<-select(WorldCities, country)
country_col<-WorldCities %>% select(country)
```

```{r}
WorldCities %>% select(region) %>% head(5)
```
```{r}
WorldCities %>% select(country) %>% unique() %>% head(9)
```
```{r}
WorldCities %>% ggplot(aes(x=population)) + geom_histogram()
##'stat_bin()' using bins=30' Pick better value with 'binwidth'
```
```{r}
WorldCities %>% ggplot(aes(x= population)) + geom_histogram() + xlab('City Population')
```
```{r}
WorldCities %>% ggplot(aes(x=population)) + geom_histogram() + xlab('City Population') + ylab('Cities') + ggtitle('Population') + theme_bw()
```

